CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -g -fsanitize=address -fno-omit-frame-pointer -MMD -MP -D_GNU_SOURCE
#CFLAGS = -Wall -Wextra -std=c99 -g -MMD -MP -D_GNU_SOURCE
LDFLAGS = -fsanitize=address
#LDFLAGS = 

SRCDIR = .
SRCS = arena.c file.c runtime.c token.c lexer.c ast.c parser.c symbol_table.c code_gen.c compiler.c debug.c type_checker.c main.c
HEADERS = arena.h file.h runtime.h token.h lexer.h ast.h parser.h symbol_table.h code_gen.h compiler.h debug.h type_checker.h
BIN_DIR = ../bin
OBJS = $(addprefix $(BIN_DIR)/, $(notdir $(SRCS:.c=.o)))
DEPS = $(OBJS:.o=.d)
TARGET = $(BIN_DIR)/sn

VPATH = $(SRCDIR)

.PHONY: all clean

all: create-bin-dir $(TARGET)

create-bin-dir:
	@mkdir -p $(BIN_DIR)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^
	@chmod +x $@

$(BIN_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@

-include $(DEPS)

# Tests
TEST_SRCDIR = tests
TEST_SRCS = $(TEST_SRCDIR)/_all_.c
TEST_OBJS = $(addprefix $(BIN_DIR)/, $(notdir $(TEST_SRCS:.c=.o)))
TEST_TARGET = $(BIN_DIR)/tests

tests: create-bin-dir $(TEST_TARGET)

$(TEST_TARGET): $(TEST_OBJS) $(BIN_DIR)/arena.o $(BIN_DIR)/debug.o $(BIN_DIR)/ast.o $(BIN_DIR)/lexer.o $(BIN_DIR)/parser.o $(BIN_DIR)/symbol_table.o $(BIN_DIR)/type_checker.o $(BIN_DIR)/token.o $(BIN_DIR)/file.o
	$(CC) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/%.o: $(TEST_SRCDIR)/%.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BIN_DIR)
