#!/bin/bash

set -euox pipefail

# Allow optimization level override via SN_OPT_LEVEL (default: -O2)
OPT_LEVEL="${SN_OPT_LEVEL:--O2}"

bin/sn samples/main.sn -o bin/hello-world -l 3 -g $OPT_LEVEL &> log/run-output.log

bin/hello-world &> log/hello-world-output.log
cat log/hello-world-output.log
